### ISSUE TITLE
Header Menü überarbeiten

### ISSUE THREAD

**Issue by PotSchmoell** [DetektivKollektiv/angular-ui#135]
Es soll folgenden neuen Menüpunkt geben

**Über codetekt** --> ausklappbar (bei Hover --> wie beim Profil) 
--> Bei Klick --> Startseite (sowohl mit Login als auch ohne)
Unterseiten:
- Der Verein --> Über uns
- Team --> Team
- Unser Ansatz --> Trust-Checking (noch nicht implementiert)
- Spenden --> betterplace (in neuem Tab)

**Comment by Th3da** [comment]
Bisher gibt's im Header-Menu nur _über uns_ - und auch nur, wenn man nicht angemeldet ist.
Dh stattdessen einen Menüpunkt _Über codetekt_ mit flyout Menu ständig, egal ob angemeldet oder nicht?

**Comment by PotSchmoell** [comment]
> Bisher gibt's im Header-Menu nur _über uns_ - und auch nur, wenn man nicht angemeldet ist. Dh stattdessen einen Menüpunkt _Über codetekt_ mit flyout Menu ständig, egal ob angemeldet oder nicht?

Genau, der Header soll immer gleich sein egal ob eingeloggt oder nicht und alle "statischen Info-Pages" sollen Unterpunkte von "über codetekt" sein.
