### ISSUE TITLE
About page: Header Illustration --> PNG durch SVG ersetzen

### ISSUE THREAD

**Issue by PotSchmoell** [DetektivKollektiv/angular-ui#137]
<img width="1740" alt="image" src="https://user-images.githubusercontent.com/25669997/147744765-ab3d7233-691d-4aa1-bf61-24bd619ef2a7.png">

**Comment by Th3da** [comment]
done - will be included in PR 119, next commit

**Comment by Th3da** [comment]
also replaced the png by svg in the finance-section (About Page):
![grafik](https://user-images.githubusercontent.com/67347402/148062563-7baa2057-bcea-4565-8249-a2748caafadd.png)
