### ISSUE TITLE
Berechnung des Vertrauensindex korrigieren

### ISSUE THREAD

**Issue by PotSchmoell** [DetektivKollektiv/angular-ui#142]
Momentane Berechnung: Score aus der API * 4 
Richtige Berechnung: (Score - 1) * 33,3

Erklärung: Der niedrigste Score, der von der API kommt ist 1. Mit der momentanen Berechnung ist das niedrigste Ergebnis, das angezeigt wird 25. Wir wollen aber eine Skala zwischen 0 und 100. Mit der neuen Berechnung, erreichen wird das.

**Comment by SandroGlueck** [comment]
Können wir das API Objekt nicht einfach um den entsprechenden Wert erweitern? Sollte ja kein großer Aufwand sein, das Objekt entsprechend zu erweitern? Dann hätten wir die Formel nicht in jedem Client.

**Comment by PotSchmoell** [comment]
> Können wir das API Objekt nicht einfach um den entsprechenden Wert erweitern?

Gute Idee - So mach ichs. :)
