### ISSUE TITLE
Landing Page: support-us-section grid alignment

### ISSUE THREAD

**Issue by SandroGlueck** [DetektivKollektiv/angular-ui#148]
Auf der Landingpage in der support-us-section nehmen die einzelnen Kacheln in der 2x2 Anordnung nicht den gesamten vertikalen Raum ein. 
Das führt speziell beim Hovern über eine der größeren Kacheln zu einem unstimmigen Bild.

![image](https://user-images.githubusercontent.com/38329766/148819856-cb0dfc37-4881-4e72-900c-ae487fb83aa2.png)

![image](https://user-images.githubusercontent.com/38329766/148819513-3a19de9e-c8b9-499f-a7c6-00f3eba63017.png)

**Comment by Th3da** [comment]
ja, ist mir auch aufgefallen.
Dann müssten wir eine feste Höhe nehmen.
Werde ich einbauen.

**Comment by SandroGlueck** [comment]
`align-items: stretch` sollte eigentlich reichen 🤔

**Comment by Th3da** [comment]
mit `align-items: stretch` sind die Icons (so wie in der vorigen Version auf dev) nicht am oberen Rand orientiert.
Mit `justify-content: flex-start` beim grid-item sind dann beide Probleme gelöst.
