### ISSUE TITLE
Internet Explorer und Safari Support

### ISSUE THREAD

**Issue by PotSchmoell** [DetektivKollektiv/angular-ui#156]
Im Frontend sollen Internet Explorer User abgefangen werden und es soll ein Hinweis angezeigt werden.
Inhalt:
- IE wird nicht unterstützt
- Bitte anderen Browser nutzen --> Vorschläge anzeigen

**Comment by SandroGlueck** [comment]
Vermutlich reicht es in der Datei `polyfills.ts` die verschiedenen `import` Statements zu aktivieren, die sich auf den IE beziehen.

**Comment by SandroGlueck** [comment]
Prinzipiell funktioniert die Seite mit einigen Anpassungen.

Allerdings gibt es weiterhin das Problem, das wir schon bei Safari festgestellt hatten.
Das MySQL Date Format entspricht nicht dem W3C Standard und führt deshalb zu Fehlern im IE.
Weiß nicht, warum es im Safari zu funktionieren scheint...

**Comment by SandroGlueck** [comment]
Tasks:

- [ ]   Umleitung für IE Nutzer in `app.component.ts`
- [ ]   Neue Vanilla HTML Seite mit Hinweis für IE Nutzer
- [ ]  Anpassung DatePipe für Safari Support
