### ISSUE TITLE
Fall bearbeiten: Nutzungsbedingungen und Datenschutzerklärung zustimmen 

### ISSUE THREAD

**Issue by Th3da** [DetektivKollektiv/angular-ui#173]
Review-page:

Beim Lösen eines Falls sollte es nicht notwendig sein, Nutzungsbedingungen und Datenschutzerklärung zuzustimmen.

Der Absatz sollte herausgenommen werden.

**Comment by PotSchmoell** [comment]
@Th3da Das schaue ich mir an, ok?
